spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        # show_sql : true : jpa 쿼리를 콘솔에 다 찍음.

# 웹 페이지별 개수 default value
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true # 인덱스 파라미터 1부터 시작함.
        # 근데 이거는 페이지 넘버가 안맞아...
logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type : trace